services:
  postgres:
    image: postgres:18
    container_name: bs14_postgres
    env_file:
      - .env.docker
    ports:
      - "127.0.0.1:55432:5432"
    volumes:
      - pg_data:/var/lib/postgresql
      - ./app/db/backup/backup.sql:/docker-entrypoint-initdb.d/backup_20_11_25.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 3

  redis:
    image: redis:8.2
    container_name: bs14_redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env.docker
    ports:
      - "127.0.0.1:6378:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3


  server:
    env_file: ".env.docker"
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
          ignore:
            - __pycache__/
            - "*.pyc"
            - "**/.pytest_cache/**"
            - "**/.venv/**"
            - "**/node_modules/**"
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./requirements.txt
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bs14_server
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  pg_data:
  redis_data:
