"""Mouse, DockingStation, Webcam und Cable hinzugefügt.

Revision ID: 19454f3fd191
Revises: 94c7ad7e9cf4
Create Date: 2025-11-14 15:32:05.479008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19454f3fd191'
down_revision: Union[str, Sequence[str], None] = '94c7ad7e9cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hdmi', sa.String(length=80), nullable=False),
    sa.Column('ethernet', sa.String(length=80), nullable=False),
    sa.Column('usb_c', sa.String(length=80), nullable=False),
    sa.Column('display_port', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('docking_stations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_port', sa.Integer(), nullable=False),
    sa.Column('hdmi', sa.Integer(), nullable=False),
    sa.Column('usb', sa.String(length=80), nullable=False),
    sa.Column('usb_c', sa.Integer(), nullable=False),
    sa.Column('thunderbolt', sa.Integer(), nullable=False),
    sa.Column('ethernet', sa.Integer(), nullable=False),
    sa.Column('audio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mouses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dpi', sa.Integer(), nullable=False),
    sa.Column('connection_style', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('battery', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webcams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.String(length=30), nullable=False),
    sa.Column('dfov_adjustable', sa.Boolean(), nullable=False),
    sa.Column('connection_style', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webcams')
    op.drop_table('mouses')
    op.drop_table('docking_stations')
    op.drop_table('cables')
    # ### end Alembic commands ###
