"""Chair und Keyboard hinzugefügt

Revision ID: 94c7ad7e9cf4
Revises: aa02faa48438
Create Date: 2025-11-14 12:29:16.160386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c7ad7e9cf4'
down_revision: Union[str, Sequence[str], None] = 'aa02faa48438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chairs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('height_max', sa.Integer(), nullable=False),
    sa.Column('height_min', sa.Integer(), nullable=False),
    sa.Column('max_weight', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyboards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_style', sa.String(length=50), nullable=False),
    sa.Column('layout', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('dimensions', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyboards')
    op.drop_table('chairs')
    # ### end Alembic commands ###
