"""Workstation hinzugefügt

Revision ID: aa02faa48438
Revises: d5fb866bd23c
Create Date: 2025-11-14 11:58:51.620327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa02faa48438'
down_revision: Union[str, Sequence[str], None] = 'd5fb866bd23c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workstations',
    sa.Column('id', sa.UUID(), nullable=True),
    sa.Column('processor', sa.String(length=50), nullable=False),
    sa.Column('operating_system', sa.String(length=50), nullable=False),
    sa.Column('memory', sa.String(length=50), nullable=False),
    sa.Column('power_usage', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('disc_memory', sa.String(length=50), nullable=False),
    sa.Column('screen_size', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('resolution_height', sa.Integer(), nullable=False),
    sa.Column('resolution_width', sa.Integer(), nullable=False),
    sa.Column('refresh_rate', sa.Integer(), nullable=False),
    sa.Column('graphics_card', sa.String(length=100), nullable=False),
    sa.Column('camera', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workstations')
    # ### end Alembic commands ###
