"""Grundgerüst fertig, spezifische Produkttabellen fehlen noch.

Revision ID: d4e01239dfe6
Revises: 584205e391d4
Create Date: 2025-11-11 12:44:59.173664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4e01239dfe6'
down_revision: Union[str, Sequence[str], None] = '584205e391d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE TYPE tier AS ENUM ('basic', 'premium', 'ultra');")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Numeric(7,2), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_product_type'), 'products', ['product_type'], unique=False)
    op.create_table('desks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('height_adjustable', sa.Boolean(), nullable=False),
    sa.Column('dimensions', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laptops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('processor', sa.String(length=50), nullable=False),
    sa.Column('operating_system', sa.String(length=50), nullable=False),
    sa.Column('memory', sa.String(length=50), nullable=False),
    sa.Column('disc_memory', sa.String(length=50), nullable=False),
    sa.Column('screen_size', sa.Integer(), nullable=False),
    sa.Column('resolution_height', sa.Integer(), nullable=False),
    sa.Column('resolution_width', sa.Integer(), nullable=False),
    sa.Column('refresh_rate', sa.Integer(), nullable=False),
    sa.Column('graphics_card', sa.String(length=100), nullable=False),
    sa.Column('camera', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resolution_height', sa.Integer(), nullable=False),
    sa.Column('resolution_width', sa.Integer(), nullable=False),
    sa.Column('latency', sa.Integer(), nullable=False),
    sa.Column('refresh_rate', sa.Integer(), nullable=False),
    sa.Column('power_usage', sa.Numeric(6, 3), nullable=False),
    sa.Column('screen_size', sa.Integer(), nullable=False),
    sa.Column('connectors', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('tier', postgresql.ENUM('basic', 'premium', 'ultra', name='tier', create_type=False, validate_strings=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'tier', name='uq_packages_department_tier')
    )
    op.create_table('package_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_package_items_quantity_positive'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'product_id', name='uq_package_items_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('package_items')
    op.drop_table('packages')
    op.drop_table('monitors')
    op.drop_table('laptops')
    op.drop_table('desks')
    op.drop_index(op.f('ix_products_product_type'), table_name='products')
    op.drop_table('products')
    op.drop_table('departments')
    op.execute('DROP TYPE IF EXISTS tier;')
    # ### end Alembic commands ###
