"""power_usage zu LaptopIn/Out hinzugefügt

Revision ID: d5fb866bd23c
Revises: d4e01239dfe6
Create Date: 2025-11-14 10:34:18.376656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5fb866bd23c'
down_revision: Union[str, Sequence[str], None] = 'd4e01239dfe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laptops', sa.Column('power_usage', sa.Numeric(precision=6, scale=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laptops', 'power_usage')
    # ### end Alembic commands ###
