"""power_usage zu DockingStation und UsageMode Enum in Package

Revision ID: f13c49f9b61f
Revises: 19454f3fd191
Create Date: 2025-11-18 15:46:09.854811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f13c49f9b61f'
down_revision: Union[str, Sequence[str], None] = '19454f3fd191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE TYPE usage_mode AS ENUM ('mobile', 'stationary');")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docking_stations', sa.Column('power_usage', sa.Numeric(precision=6, scale=3), nullable=False))
    op.add_column('packages', sa.Column('usage_mode', postgresql.ENUM('mobile', 'stationary', name='usage_mode'), nullable=False))
    op.drop_constraint(op.f('uq_packages_department_tier'), 'packages', type_='unique')
    op.create_unique_constraint('uq_packages_department_tier_usage_mode', 'packages', ['department_id', 'tier', 'usage_mode'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_packages_department_tier_usage_mode', 'packages', type_='unique')
    op.create_unique_constraint(op.f('uq_packages_department_tier'), 'packages', ['department_id', 'tier'], postgresql_nulls_not_distinct=False)
    op.drop_column('packages', 'usage_mode')
    op.drop_column('docking_stations', 'power_usage')
    op.execute('DROP TYPE IF EXISTS usage_mode;')
    # ### end Alembic commands ###
